### PR TITLE
Add CS generic type to ASForR1CSNark verifier

### PR DESCRIPTION
**Pull request by Will-Lin4**
When using the verifier gadget of `ASForR1CSNark`, implementations previously needed to specify the constraint synthesizer through including `<... as ASVerifierGadget<..., ASForR1CSNark<..., CS>>`, which is very lengthy. Including the type directly in the verifier gadget can prevent this issue.

### CODE REVIEW

**Comment by Will-Lin4** [comment]
The CI is failing because a nightly test is detecting an unused variable. This issue is fixed in #24. After that PR is merged, we can rerun the tests.

**Comment by Pratyush** [comment]
I think we should just remove the `CS: ConstraintSynthesizer` everywhere; it's not a property that we have to be generic over. (We are already generic over any R1CS.)

**Comment by Will-Lin4** [comment]
We need `CS: ConstraintSynthesizer` to be a generic parameter for the accumulation scheme because the AS indexer needs to take in a `ConstraintSynthesizer`. Since we can't add parameters to that function, we need to have it elsewhere, so it is a generic parameter.

**Comment by Pratyush** [comment]
Hmm I think we should just directly take in a R1CS index (and instance/witness where relevant)

**Comment by Will-Lin4** [comment]
> Hmm I think we should just directly take in a R1CS index (and instance/witness where relevant)

Do you mean replacing the predicate param or index (https://github.com/arkworks-rs/accumulation/blob/4d3dda736b323f6f8541bd13cee4db3d8d7b2a9b/src/r1cs_nark_as/mod.rs#L672) to be just the keys outputted by the R1CS NARK indexer?

**Comment by Pratyush** [comment]
Yup!

**Comment by Will-Lin4** [comment]
This PR is no longer needed with the removal of CS from the generic parameters. See #31

**Pull request closed without merging**
